### ISSUE TITLE
It's not working Samsung 6 Edge  android 5.1.1 

### ISSUE THREAD

**Issue by Himanshu4003** [tekinarslan/AndroidPdfViewer#16]
I am getting below crash when using App with following library : 

``` Java 
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.engagebeyond.sasol-1/base.apk"],nativeLibraryDirectories=[/data/app/com.engagebeyond.sasol-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libmupdf.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:366)
	at java.lang.System.loadLibrary(System.java:988)
	at com.artifex.mupdflib.MuPDFCore.&lt;clinit&gt;(MuPDFCore.java:14)
	at com.artifex.mupdflib.MuPDFActivity.openFile(MuPDFActivity.java:233)
	at com.artifex.mupdflib.MuPDFActivity.onCreate(MuPDFActivity.java:445)
	at android.app.Activity.performCreate(Activity.java:6500)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218)
	at android.app.ActivityThread.access$1000(ActivityThread.java:198)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6837)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

Can you tell me how to build arm64 for mupdf ?

**Comment by frankjunqi** [comment]
I also happen this crash.
Can you tell me how to build arm64 for mupdf ?
